### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by scambier** [scambier/ghost-static#1]
Characters beyond ascii are not correctly encoded

**Comment by scambier** [comment]
https://github.com/scambier/ghost-static/commit/ed279d6b444721e6dd4a950f3c28dee8b613e1ea

**Comment by 1a57danc3** [comment]
https://github.com/nwjs-community/nw-builder/issues/75

➜  Ghost sudo ghost-static
env: node\r: No such file or directory
