### ISSUE TITLE
What's mean with Ghost directory path? ghost or ghost/core ?

### ISSUE THREAD

**Issue by 1a57danc3** [scambier/ghost-static#4]
Create a `ghost-static.json` in your Ghost directory???

➜  ghost ghost-static
env: node\r: No such file or directory

**Comment by scambier** [comment]
- Follow this guide to install Ghost locally: https://docs.ghost.org/docs/install-local
- Install ghost-static globally
- Create the ghost-static.json inside the Ghost directory. It's the same directory from where you run `ghost start`
- Start Ghost
- Type `ghost-static` to scrape your local instance

**Comment by 1a57danc3** [comment]
thx!
